name: wradlib-dev
channels:
  - conda-forge
dependencies:
  - python=3.13
  - codecov
  - cartopy
  - pooch
  - pytest-cov
  - rioxarray
  - setuptools
  - open-radar-data
  - scipy
  - pip
  - xradar[version='>=0.8.0']
  - lat_lon_parser
  - netcdf4
  - h5py
  - pytest-xdist
  - pyproj
  - matplotlib-base
  - pytest-sugar
  - deprecation
  - coverage
  - bottleneck
  - libgdal-netcdf
  - libgdal-hdf5
  - pytest
  - numpy
  - pytest-doctestplus
  - xmltodict
  - dask
  - xarray[version='>=2024.10.0']
  - gdal
  - requests
  - h5netcdf
  - pint
  - tqdm
  - jupytext
  - nc-time-axis
  - psutil
  - cmweather
  - notebook
  - pint-xarray
  - nbconvert
  - geopandas
  - myst-nb
  - pydata-sphinx-theme
  - sphinx_rtd_theme
  - sphinx
  - sphinx-book-theme[version='>=1.0']
  - ipykernel
  - sphinxcontrib-bibtex
  - nbsphinx
  - sphinx-copybutton
  - linkify-it-py
  - setuptools_scm
  - accessible-pygments
  - pandoc
  - git
  - pre-commit
  - diff-cover
  - wradlib_data
  - nomkl
  - proj-data
